fix: Bypass test authentication
Update bypass authentication method for tests to pass successfully.

Cause: 'force_authenticate' method did not bypass client authentication.
Error: <HttpResponseForbidden status_code=403> response from view.
Fix: Use 'credentials' method to set auth header in test sub-requests.

NB: Prefer using 'credentials' over 'force_authenticate' method:
  - Avoid passing the token directly to APIClient.
  - More secure way to bypass OAuth2 authentication flow.